export const CAR_NAME_PARTS: Record<string, string[]> = {
  Tesla: [
    'Model S',
    'Model 3',
    'Model X',
    'Model Y',
    'Roadster',
    'Cybertruck',
    'Semi',
    'Model 2',
    'Model Q',
    'Model A',
  ],
  Ford: [
    'Mustang',
    'F-150',
    'Explorer',
    'Bronco',
    'Ranger',
    'Edge',
    'Expedition',
    'Maverick',
    'Escape',
    'Galaxy',
  ],
  BMW: ['M3', 'M5', 'X5', 'i8', '330i', '750i', 'Z4', 'X7', 'M8', 'iX'],
  Toyota: [
    'Camry',
    'Supra',
    'Land Cruiser',
    'Corolla',
    'GR86',
    'RAV4',
    'Highlander',
    'Tundra',
    'Avalon',
    'Sequoia',
  ],
  Honda: [
    'Civic',
    'NSX',
    'Accord',
    'CR-V',
    'Integra',
    'Pilot',
    'Ridgeline',
    'Passport',
    'HR-V',
    'Odyssey',
  ],
  Chevrolet: [
    'Corvette',
    'Camaro',
    'Silverado',
    'Blazer',
    'Equinox',
    'Traverse',
    'Tahoe',
    'Suburban',
    'Colorado',
    'Trax',
  ],
  Mercedes: [
    'C-Class',
    'G-Class',
    'AMG GT',
    'E-Class',
    'S-Class',
    'GLE',
    'GLC',
    'A-Class',
    'CLA',
    'EQS',
  ],
  Audi: ['R8', 'RS6', 'A4', 'Q7', 'TT', 'A6', 'Q5', 'e-tron', 'RS3', 'SQ8'],
  Porsche: [
    '911',
    'Cayenne',
    'Panamera',
    'Taycan',
    'Macan',
    'Boxster',
    'Cayman',
    '718',
    'Spyder',
    'GT3',
  ],
  Ferrari: [
    'F40',
    '488',
    'Roma',
    'SF90',
    'Purosangue',
    '296',
    'F8',
    '812',
    'Portofino',
    'LaFerrari',
  ],
};

export const RANDOM_CARS_COUNT = 100;
